### ISSUE TITLE
Bolt usage?

### ISSUE THREAD

**Issue by giorgiovilardo** [ivoputzer/slack.codin.gg#1]
I was looking for documentation on `@slack/events-api` [here](https://www.npmjs.com/package/@slack/events-api), and it says that's in EOL since may 2021.

The suggested replacement is [Bolt](https://github.com/slackapi/bolt-js).

WDYT?

**Comment by ivoputzer** [comment]
shouldn't be too difficult to switch underlying lib. this would also allow to make use of new features such as show the typing indicator while the request towards openai is running 👍
